import { NotificationEvent } from '../enums/notification-event.enum';
import { I18N_NOTIFICATIONS } from '@/shared/constants/i18n';

const NOTIFICATION_EVENT_TITLE_MAPPER: Record<string, string> = {
  [NotificationEvent.AUTH_LOGIN]: I18N_NOTIFICATIONS.TITLES.AUTH_LOGIN,
  [NotificationEvent.ORDER_CREATED]: I18N_NOTIFICATIONS.TITLES.ORDER_CREATED,
  [NotificationEvent.ORDER_FAILED_UPON_CREATING]:
    I18N_NOTIFICATIONS.TITLES.ORDER_FAILED_UPON_CREATING,
  [NotificationEvent.ORDER_STATUS_CHANGED]:
    I18N_NOTIFICATIONS.TITLES.ORDER_STATUS_CHANGED,
  [NotificationEvent.ORDER_CANCELED]: I18N_NOTIFICATIONS.TITLES.ORDER_CANCELED,
  [NotificationEvent.ORDER_REFUNDED]: I18N_NOTIFICATIONS.TITLES.ORDER_REFUNDED,
  [NotificationEvent.ORDER_PAID]: I18N_NOTIFICATIONS.TITLES.ORDER_PAID,
  [NotificationEvent.ORDER_FAILED]: I18N_NOTIFICATIONS.TITLES.ORDER_FAILED,
  [NotificationEvent.ORDER_PROCESSED]: I18N_NOTIFICATIONS.TITLES.ORDER_PROCESSED,
  [NotificationEvent.ORDER_SHIPPED]: I18N_NOTIFICATIONS.TITLES.ORDER_SHIPPED,
  [NotificationEvent.ORDER_DELIVERED]: I18N_NOTIFICATIONS.TITLES.ORDER_DELIVERED,
};

const NOTIFICATION_EVENT_MESSAGE_MAPPER: Record<string, string> = {
  [NotificationEvent.AUTH_LOGIN]: I18N_NOTIFICATIONS.MESSAGES.AUTH_LOGIN,
  [NotificationEvent.ORDER_CREATED]: I18N_NOTIFICATIONS.MESSAGES.ORDER_CREATED,
  [NotificationEvent.ORDER_FAILED_UPON_CREATING]:
    I18N_NOTIFICATIONS.MESSAGES.ORDER_FAILED_UPON_CREATING,
  [NotificationEvent.ORDER_STATUS_CHANGED]:
    I18N_NOTIFICATIONS.MESSAGES.ORDER_STATUS_CHANGED,
  [NotificationEvent.ORDER_CANCELED]: I18N_NOTIFICATIONS.MESSAGES.ORDER_CANCELED,
  [NotificationEvent.ORDER_REFUNDED]: I18N_NOTIFICATIONS.MESSAGES.ORDER_REFUNDED,
  [NotificationEvent.ORDER_PAID]: I18N_NOTIFICATIONS.MESSAGES.ORDER_PAID,
  [NotificationEvent.ORDER_FAILED]: I18N_NOTIFICATIONS.MESSAGES.ORDER_FAILED,
  [NotificationEvent.ORDER_PROCESSED]: I18N_NOTIFICATIONS.MESSAGES.ORDER_PROCESSED,
  [NotificationEvent.ORDER_SHIPPED]: I18N_NOTIFICATIONS.MESSAGES.ORDER_SHIPPED,
  [NotificationEvent.ORDER_DELIVERED]: I18N_NOTIFICATIONS.MESSAGES.ORDER_DELIVERED,
};

export class NotificationEventToTemplateMapper {
  static getTitleTemplate(event: NotificationEvent): string {
    return NOTIFICATION_EVENT_TITLE_MAPPER[event];
  }

  static getMessageTemplate(event: NotificationEvent): string {
    return NOTIFICATION_EVENT_MESSAGE_MAPPER[event];
  }
}
