const MILISECOND = 1;
const SECOND = 1000 * MILISECOND;
const MINUTE = 60 * SECOND;
const HOUR = 60 * MINUTE;
const DAY = 24 * HOUR;

export const CACHE_TTL = {
  DEFAULT: 5 * MINUTE,

  LOCK: 5 * SECOND,

  LIST: 5 * MINUTE,

  IDEMPOTENCY: DAY,

  AUTH_BLACKLIST: 15 * MINUTE,

  JOB_LOCK: 30 * SECOND,
} as const;
