const SECONDS = 1000;
const MINUTES = 60 * SECONDS;
const HOURS = 60 * MINUTES;
const DAYS = 24 * HOURS;

export const CACHE_TTL = {
  DEFAULT: 5 * MINUTES,

  LOCK: 5 * SECONDS,

  LIST: 5 * MINUTES,

  IDEMPOTENCY: 1 * DAYS,

  PAYMENT_IDEMPOTENCY_TTL: 1 * DAYS,

  AUTH_BLACKLIST: 15 * MINUTES,

  JOB_LOCK: 30 * SECONDS,

  JOB_STRATEGY: 1 * HOURS,
} as const;
