export enum OutboxType {
  // Order jobs
  ORDER_PROCESS = 'ORDER_PROCESS',
  ORDER_SHIP = 'ORDER_SHIP',
  ORDER_DELIVER = 'ORDER_DELIVER',
  ORDER_CANCEL = 'ORDER_CANCEL',

  // Events
  EVENTS_NOTIFY_USER = 'EVENTS_NOTIFY_USER',
}
