export enum OutboxType {
  // Order jobs
  ORDER_PROCESS = 'ORDER_PROCESS',
  ORDER_SHIP = 'ORDER_SHIP',
  ORDER_DELIVER = 'ORDER_DELIVER',
  ORDER_CANCEL = 'ORDER_CANCEL',
  ORDER_REFUND = 'ORDER_REFUND',

  // Events
  EVENTS_NOTIFY_USER = 'EVENTS_NOTIFY_USER',

  // Payment jobs
  PAYMENT_CREATE_CUSTOMER = 'PAYMENT_CREATE_CUSTOMER',
  PAYMENT_UPDATE_CUSTOMER = 'PAYMENT_UPDATE_CUSTOMER',
  PAYMENT_DELETE_CUSTOMER = 'PAYMENT_DELETE_CUSTOMER',
}
