export enum OrderJob {
  PROCESS_ORDER = 'PROCESS_ORDER',
  SHIP_ORDER = 'SHIP_ORDER',
  DELIVER_ORDER = 'DELIVER_ORDER',
  CANCEL_ORDER = 'CANCEL_ORDER',
  NOTIFICATION_ORDER = 'NOTIFICATION_ORDER',
}
